# Generated by Django 2.2.4 on 2019-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_address',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='Null', max_length=14),
        ),
    ]
