# Generated by Django 2.2.4 on 2019-08-31 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0003_buildings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buildings',
        ),
    ]
