# Generated by Django 2.2.4 on 2019-08-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0004_delete_buildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(default='Null', max_length=200)),
                ('building_name', models.CharField(default='Null', max_length=200)),
                ('contact_number', models.CharField(default='Null', max_length=200)),
            ],
        ),
    ]
